set_property SRC_FILE_INFO {cfile:/home/jacoboffersen/advanced_programmable_electronics/APE_Exam/APE_Exam.srcs/constrs_1/imports/constrs_1/Arty-S7-50-Rev-B-Master.xdc rfile:../../../../../APE_Exam.srcs/constrs_1/imports/constrs_1/Arty-S7-50-Rev-B-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK100MHZ]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports RX_I]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI_I]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI_O]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCLK_I]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_SCLK_O]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports TX_O]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name CLKFBIN -source [get_pins FPGA1_inst/clocking_1_inst/MMCME2_BASE_48_inst/CLKIN1] -multiply_by 1 -add -master_clock sys_clk_pin [get_pins FPGA1_inst/clocking_1_inst/MMCME2_BASE_48_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_spi -source [get_pins FPGA1_inst/clocking_1_inst/MMCME2_BASE_48_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 0.120 0.240} -add -master_clock sys_clk_pin [get_pins FPGA1_inst/clocking_1_inst/MMCME2_BASE_48_inst/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_A -source [get_pins FPGA1_inst/clocking_1_inst/MMCME2_BASE_48_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 27.000 54.000} -add -master_clock sys_clk_pin [get_pins FPGA1_inst/clocking_1_inst/MMCME2_BASE_48_inst/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_feedback -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock sys_clk_pin [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_pixel_unbuffered -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 1.667 3.333} -add -master_clock sys_clk_pin [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_x5pixel_unbuffered -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKIN1] -edges {1 2 3} -edge_shift {0.000 -3.889 -7.778} -add -master_clock sys_clk_pin [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_x5pixelinv_unbuffered -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKIN1] -edges {1 2 3} -edge_shift {1.111 -2.778 -6.667} -add -master_clock sys_clk_pin [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720A/PLL_BASE_inst/CLKOUT2]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_feedback_1 -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKIN1] -multiply_by 1 -add -master_clock clock_pixel_unbuffered [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_pixel_unbuffered_1 -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKIN1] -multiply_by 10 -add -master_clock clock_pixel_unbuffered [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_x5pixel_unbuffered_1 -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKIN1] -multiply_by 5 -add -master_clock clock_pixel_unbuffered [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clock_x5pixelinv_unbuffered_1 -source [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKIN1] -edges {1 2 3} -edge_shift {1.333 -4.000 -9.333} -add -master_clock clock_pixel_unbuffered [get_pins FPGA2_inst/clocking_2_inst/clock_eng_1280_720B/PLL_BASE_inst/CLKOUT2]
